<?php

namespace Blueways\BwEmail\Controller;

use TYPO3\CMS\Core\Imaging\Icon;
use TYPO3\CMS\Backend\Template\Components\ButtonBar;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Backend\Utility\BackendUtility;

class ViewModuleController extends \TYPO3\CMS\Viewpage\Controller\ViewModuleController
{

    /**
     *
     */
    protected function registerButtons()
    {
        parent::registerButtons(); // TODO: Change the autogenerated stub

        if ($this->isEmailType()) {
            $buttonBar = $this->view->getModuleTemplate()->getDocHeaderComponent()->getButtonBar();
            $refreshButton = $buttonBar->makeLinkButton()
                ->setHref('javascript:document.getElementById(\'tx_viewpage_iframe\').contentWindow.location.reload(true);')
                ->setTitle($this->getLanguageService()->sL('LLL:EXT:bw_email/Resources/Private/Language/locallang.xlf:sendMail'))
                ->setIcon($this->view->getModuleTemplate()->getIconFactory()->getIcon('actions-email',
                    Icon::SIZE_SMALL));
            $buttonBar->addButton($refreshButton, ButtonBar::BUTTON_POSITION_LEFT, 1);
        }
    }

    /**
     * @return bool
     */
    protected function isEmailType()
    {
        $pageIdToShow = (int)GeneralUtility::_GP('id');
        $pageRecord = BackendUtility::getRecord('pages', $pageIdToShow);

        return $pageRecord['doktype'] === 117;
    }
}
